### ISSUE TITLE
Scaffold vite + vue

### ISSUE THREAD

**Issue by Boshen** [oxc-project/playground#2]
@eryue0220

**Comment by eryue0220** [comment]
@Boshen Hi, the repo is fully empty and I could not clone. 😂

![image](https://github.com/oxc-project/playground/assets/3050418/228976ac-b5e3-4633-92e4-96bce061a517)

**Comment by Boshen** [comment]
> @Boshen Hi, the repo is fully empty and I could not clone. 😂
> 
> ![image](https://private-user-images.githubusercontent.com/3050418/330642600-228976ac-b5e3-4633-92e4-96bce061a517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzgxNzMsIm5iZiI6MTcxNTc3Nzg3MywicGF0aCI6Ii8zMDUwNDE4LzMzMDY0MjYwMC0yMjg5NzZhYy1iNWUzLTQ2MzMtOTJlNC05NmJjZTA2MWE1MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTI1NzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU1YTE0NDIxMDE0ZTQxZjc0MmY4Y2FlNTNiNDk2ZDVjODExOGJkOWYxYThhNDgyOWE2ZjE0ZGVhMTE1NGNkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9lh_sAGP_H7OdCXZyBnnZZdUwfWunoxFWIWIdUcauMk)

Excuse me for the inconvenience, it's updated.
