### ISSUE TITLE
If code in the uri is too long, github pages will return 414 error

### ISSUE THREAD

**Issue by bytemain** [oxc-project/playground#20]
![CleanShot 2024-08-20 at 17 16 26@2x](https://github.com/user-attachments/assets/f4144054-5ced-4397-81ff-8b1c63728582)

see:
- https://stackoverflow.com/questions/64565060/what-is-the-maximum-length-for-a-github-pages-uri

**Comment by sxzz** [comment]
Resolved now. Using `location.hash` instead of query.
