### ISSUE TITLE
Playground does not update when change the input code

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/playground#32]
The old playground used to update AST as you changed the source code. The new one doesn't appear to (at least in Chrome 127 on Mac OS).

**Comment by Boshen** [comment]
This is probably due to my change to `oxc_wasm`.

**Comment by Boshen** [comment]
I'll work on this.

**Comment by Boshen** [comment]
It seems like our diagnostics are not getting printed, its reporting builtin tsc diagnostics instead.

**Comment by Boshen** [comment]
>  if you put in some code which is a syntax error, then the AST gets stuck and does not update any more

It produces an empty AST if the syntax error is non-recoverable, so it looks "stuck".

**Comment by sxzz** [comment]
It seems the issue cannot be reproduced in the latest version. Please try again or provide a screen recording.

**Comment by overlookmotel** [comment]
Yes, working for me now. I'm not sure if it was a genuine bug, or Boshen mentioned caching might not have been working properly so I might have been seeing an old version of playground. Thanks.
