### ISSUE TITLE
Use shiki for monaco highlighting

### ISSUE THREAD

**Issue by IWANABETHATGUY** [oxc-project/playground#37]
we can use shiki for monaco highlighting

_Originally posted by @sxzz in https://github.com/oxc-project/playground/issues/36#issuecomment-2328172572_

**Comment by sxzz** [comment]
I tried the PR #35 you previously optimized bundle size for Monaco Editor. I found that not only was highlighting missing, but also code suggestions.

If using this simplified version of Monaco editor, it would be even worse than using CodeMirror. So for a good DX, I think the size is worth it.
